# Generated by Django 3.0.3 on 2020-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
