# Generated by Django 3.0.3 on 2020-08-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_new', '0004_userdevices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevices',
        ),
    ]
