# Generated by Django 3.0.3 on 2020-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDevices', '0002_userdevices_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevices',
            name='connection_date',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
