# Generated by Django 3.0.3 on 2020-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDevices', '0003_auto_20200819_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevices',
            name='device_water_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
