# Generated by Django 3.0.3 on 2020-08-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDevices', '0005_auto_20200819_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevices',
            old_name='connection_date',
            new_name='connection_Date',
        ),
        migrations.RenameField(
            model_name='userdevices',
            old_name='device_water_level',
            new_name='device_WaterLevel',
        ),
    ]
