# Generated by Django 3.0.3 on 2020-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDevices', '0006_auto_20200820_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevices',
            name='device_WaterLevel',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
