# Generated by Django 3.0.3 on 2020-08-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('device_picture', models.URLField()),
                ('device_description', models.CharField(max_length=250)),
            ],
        ),
    ]
