# Generated by Django 3.0.3 on 2020-08-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userDevices', '0007_auto_20200820_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_1_ID', models.IntegerField(blank=True, null=True)),
                ('spot_2_ID', models.IntegerField(blank=True, null=True)),
                ('spot_3_ID', models.IntegerField(blank=True, null=True)),
                ('spot_4_ID', models.IntegerField(blank=True, null=True)),
                ('spot_5_ID', models.IntegerField(blank=True, null=True)),
                ('spot_6_ID', models.IntegerField(blank=True, null=True)),
                ('currentSpotSize', models.IntegerField(blank=True, null=True)),
                ('uDevice_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDevices.UserDevices')),
            ],
        ),
    ]
